### ISSUE TITLE
Apache Access Log samples report parsing errors

### ISSUE THREAD

**Issue by RichardParkinson** [Nastel/tnt4j-streams#1]
Both the tnt4j-streams-0.1-beta\samples\apache-access-multi-log and tnt4j-streams-0.1-beta\samples\apache-access-single-log show parsing errors. 

The activity stream log is built but it appears nothing was streamed to jKool

[Archive.zip](https://github.com/Nastel/tnt4j-streams/files/105243/Archive.zip)

**Comment by charleyrich** [comment]
Hi Richard,

How functional is the hdfs collector at this point?  Could it be used in a trial?

Regards,

Charley

**Comment by RichardParkinson** [comment]
I have not tested it yet as I have to set up a hadoop environment or least get the binaries. Running the hdfs-file-stream sample on Windows failed because of missing hadoop binaries. I am just looking at this now

Richard Parkinson
Nastel Technologies, Inc.<http://www.nastel.com/>

mobile: +44 7747 634730

mailto: rparkinson@nastel.com<mailto:amavashev@nastel.com>


<http://www.nastel.com/>

[cid:image001.png@01D0E4B9.8F62BD80]
The information contained in this e-mail and in any attachment is confidential and
is intended solely for the use of the individual or entity to which it is addressed.
Access, copying, disclosure or use of such information by anyone else is unauthorized.
If you are not the intended recipient, please delete the e-mail and refrain from use of such information.

On 26 Jan 2016, at 16:42, Charley Rich <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Richard,

How functional is the hdfs collector at this point? Could it be used in a trial?

Regards,

Charley

**Comment by RichardParkinson** [comment]
The hadoop installation on Windows is not trivial so will take a while, I need a number of other components installed before it can be built.

Do we have any dependencies on specific versions of hadoop?


Richard Parkinson
Nastel Technologies, Inc.<http://www.nastel.com/>

mobile: +44 7747 634730

mailto: rparkinson@nastel.com<mailto:amavashev@nastel.com>


<http://www.nastel.com/>

[cid:image001.png@01D0E4B9.8F62BD80]
The information contained in this e-mail and in any attachment is confidential and
is intended solely for the use of the individual or entity to which it is addressed.
Access, copying, disclosure or use of such information by anyone else is unauthorized.
If you are not the intended recipient, please delete the e-mail and refrain from use of such information.

On 26 Jan 2016, at 17:26, Richard Parkinson <rparkinson@nastel.com<mailto:rparkinson@nastel.com>> wrote:

I have not tested it yet as I have to set up a hadoop environment or least get the binaries. Running the hdfs-file-stream sample on Windows failed because of missing hadoop binaries. I am just looking at this now

Richard Parkinson
Nastel Technologies, Inc.<http://www.nastel.com/>

mobile: +44 7747 634730

mailto: rparkinson@nastel.com<mailto:amavashev@nastel.com>


<http://www.nastel.com/>

<image001.png>
The information contained in this e-mail and in any attachment is confidential and
is intended solely for the use of the individual or entity to which it is addressed.
Access, copying, disclosure or use of such information by anyone else is unauthorized.
If you are not the intended recipient, please delete the e-mail and refrain from use of such information.

On 26 Jan 2016, at 16:42, Charley Rich <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Richard,

How functional is the hdfs collector at this point? Could it be used in a trial?

Regards,

Charley

**Comment by kausandr** [comment]
As activties log shows, events where stremed to cloud. In your cloud dashboard adjust time range to year 2004 (as event start time is in that range). After this events should apear ;)

**Comment by RichardParkinson** [comment]
Been back to 2004 and nothing, will try again……..I doing my basic testing using subscribe……does subscribe use a timeframe? I would expect subscribe just to display whatever it receives regardless of date…….

Richard Parkinson
Nastel Technologies, Inc.<http://www.nastel.com/>

mobile: +44 7747 634730

mailto: rparkinson@nastel.com<mailto:amavashev@nastel.com>


<http://www.nastel.com/>

[cid:image001.png@01D0E4B9.8F62BD80]
The information contained in this e-mail and in any attachment is confidential and
is intended solely for the use of the individual or entity to which it is addressed.
Access, copying, disclosure or use of such information by anyone else is unauthorized.
If you are not the intended recipient, please delete the e-mail and refrain from use of such information.

On 26 Jan 2016, at 19:25, Andrius Kausinis <notifications@github.com<mailto:notifications@github.com>> wrote:


As activties log shows, events where stremed to cloud. In your cloud dashboard adjust time range to year 2004 (as event start time is in that range). After this events should apear ;)
