### ISSUE TITLE
run.bat - The system cannot find the path specified. 

### ISSUE THREAD

**Issue by igorkry** [Nastel/tnt4j-streams#10]
>Jkool\TNT4J\tnt4j-streams-master\tnt4j-streams-wmq\samples\trace-events>run.bat
>Jkool\TNT4J\tnt4j-streams-master\tnt4j-streams-wmq\samples\trace-events>..\..\bin\tnt4j-streams.bat -f:tnt-data-source.xml
The system cannot find the path specified.

need one more level up
..\..\bin\tnt4j-streams.bat -f:tnt-data-source.xml

**Comment by kausandr** [comment]
these bat files are meant to be used after streams build. 

now what i see is that you are trying to run from unbuild project structure.
