### ISSUE TITLE
tnt4j-streams-wmq cannot connect to QMGR

### ISSUE THREAD

**Issue by Jens1977** [Nastel/tnt4j-streams#16]
When I run the message-broker/run.sh (ubuntu 16.04) I get the following error:

Failed to connect to queue manager: com.ibm.mq.MQException: MQJE001: Completion Code '2', Reason '2495'. (MQRC_MODULE_NOT_FOUND)

My QMGR is started.

I think it has something to do with the app not finding mqjbnd, or the right version of it. I tried pointing my MQ_JAVA_LIB_PATH to the 32-bit and the 64-bit lib-subfolders, but that did not help. Any ideas on how to solve this?

**Comment by rnikula** [comment]
This is a configuration error trying to load the java bindings.   Assuming you have installed them correctly, the client is a separate install on Linux and Ubuntu support requires special setup for MQ, then it is likely the path is not configured correctly.  See http://www-01.ibm.com/support/docview.wss?uid=swg21607934 and https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_8.0.0/com.ibm.mq.dev.doc/q030610_.htm

**Comment by Jens1977** [comment]
@rnikula, I tried pointing both the PATH and MQ_JAVA_LIB_PATH to the 32-bit and after that to the 64-bit lib-path, but no luck.
Do you know which one of those variables is used by the client?

**Comment by rnikula** [comment]
MQ_JAVA_LIB_PATH is only used by some MQ applications that are designed to use it and I don't believe broker does.  Path should be used by the broker startup, although I do see some cases where it didn't work.  As noted, this assumes you installed the client software correctly.     There are a variety of factors and these are not related directly to the tnt4j streams for mq so not sure this is the appropriate place to troubleshoot them.

**Comment by kausandr** [comment]
In case you have ibm.mq.xxxxxx.jar libs under `MQ_JAVA_LIB_PATH`, edit sample run script file and add `MQ_JAVA_LIB_PATH` to classpath.

**Comment by Jens1977** [comment]
I made it work by adding -Djava.library.path=/opt/mqm/java/lib64 to TNT4JOPTS in tnt4j-streams.sh
