### ISSUE TITLE
Stream for activity-trace needs a way to suppress activity trace based on MQRC 

### ISSUE THREAD

**Issue by igorkry** [Nastel/tnt4j-streams#17]
tnt4j Stream (e.i. for activity-trace) need a way to suppress activity trace based on MQRC  to limit unnecessary data coming to jKool.
for instance, MQRC - 2033 - MQRC_NO_MSG_AVAILABLE 
or MQRC - 30737 which is observed on qmgr 7.5.0.7 and IIBv10 when broker application issues "MQCALLBACK"  .

**Comment by kausandr** [comment]
use WMQ trace stream property `ExcludedRC`.

**Comment by igorkry** [comment]
i think your suggestion is to use this property in the tnt-data-source.xml.
can you provide an example
thanks

**Comment by igorkry** [comment]
i tried adding following property in tnt-data-source.xml without success:
<property name="ExcludedRC" value="2033|30737|2079"/>

**Comment by kausandr** [comment]
Sample:

<property name="ExcludedRC" value="MQRC_NO_MSG_AVAILABLE|30737"/>

See commented outnsample

**Comment by kausandr** [comment]
Sample:
```xml
<property name="ExcludedRC" value="MQRC_NO_MSG_AVAILABLE|30737"/>
```

See commented out sample configuration lines.

And you need to build latest cose to use it.

**Comment by igorkry** [comment]
So the property example I used is correct one, but requires rebuild of the code. That explains it why it did not work.
I don’t build the code for tnt4j streams. I would now how if I had instructions.  My expectation is that it is should come from development team. •

Regards,

Igor
