### ISSUE TITLE
need to present activity-trace message payload in text format

### ISSUE THREAD

**Issue by igorkry** [Nastel/tnt4j-streams#18]
if this is possible at all to present activity-trace message payload in text format
example received from activity trace  (MQGACF_ACTIVITY_TRACE.MQBACF_MESSAGE_DATA):

PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxuczI6THFtUmVxdWVzdCB4bWxuczpuczI9Imh0dHA6Ly93d3cuYm55bWVsbG9uLmNvbSI+PE1ldGFkYXRhPjxNZXNzYWdlUmVmZXJlbmNlSWQ+MTk1MTMyNzM2OC0wbGlxdWlkaXR5bWFuPC9NZXNzYWdlUmVmZXJlbmNlSWQ+PFJlcXVlc3RUeXBlPk5FVzwvUmVxdWVzdFR5cGU+PHRuczpBQUxfQUNLMV9BQ1RJT04+TkVXPC90bnM6QUFMX0FDSzFfQUNUSU9OPjx0bnM6QUFMX0FDSzJfQUNUSU9OPk9MRDwvdG5zOkFBTF9BQ0syX0FDVElPTj48UmVxdWVzdFN1YlR5cGU+PC9SZXF1ZXN0U3ViVHlwZT48U291cmNlU3lzdGVtPkVQSDwvU291cmNlU3lzdGVtPjxNZXNzYWdlVHlwZT4yMDI8L01lc3NhZ2VUeXBlPjxTb3VyY2VTeXN0ZW1SZWY+RVBIMTIzNDU2SUdPUjwvU291cmNlU3lzdGVtUmVmPjxTb3VyY2VTeXN0ZW1Dcm9zc1JlZj5VU0Q0NTA2MTMyMVdXV1c8L1NvdXJjZVN5c3RlbUNyb3NzUmVmPjxSZXF1ZXN0VGltZXN0YW1wPjIwMTUtMDYtMTcgMTY6MTc6NDIuMDQyPC9SZXF1ZXN0VGltZXN0YW1wPjwvTWV0YWRhdGE+PFBheW1lbnRPYmplY3Q+PFRyYW5zYWN0aW9uRGV0YWlscz48Q3VycmVuY3k+VVNEPC9DdXJyZW5jeT48QW1vdW50PjMyMTc4OTAuNjk8L0Ftb3VudD48VmFsdWVEYXRlPjIwMTUtMDYtMTc8L1ZhbHVlRGF0ZT48U291cmNlU3lzdGVtUHJpb3JpdHk+MTwvU291cmNlU3lzdGVtUHJpb3JpdHk+PC9UcmFuc2FjdGlvbkRldGFpbHM+PE5vc3Ryb0RldGFpbHM+PE5vc3Ryb0REQVN5c3RlbT5NTUQ8L05vc3Ryb0REQVN5c3RlbT48Tm9zdHJvQWNjb3VudD4zNTgzMjA5NzAwPC9Ob3N0cm9BY2NvdW50PjxOb3N0cm9CcmFuY2g+MDQ8L05vc3Ryb0JyYW5jaD48Tm9zdHJvRW50aXR5PjAwMjc2PC9Ob3N0cm9FbnRpdHk+PE5vc3Ryb0N1dE9mZlRpbWU+MjAxNTA2MTcxODU5MDA8L05vc3Ryb0N1dE9mZlRpbWU+PC9Ob3N0cm9EZXRhaWxzPjxDbGllbnREZQ==

**Comment by kausandr** [comment]
Use `<field-transform>` to transform `byte[]` value to `String`. For example:
```xml
<field name="Message" ...>
    <field-transform name="toUpper" lang="groovy">
        $fieldValue == null ? null : new String ($fieldValue, "UTF-8")
    </field-transform>
</field>
```
