### ISSUE TITLE
Ability to provide field map ranges for numeric fields

### ISSUE THREAD

**Issue by amavashev** [Nastel/tnt4j-streams#2]
Ability to provide field map ranges for numeric fields. Examples: range [0-100] (number between 0-100, both inclusive), 100+ n >= 100, 100-  n <= 100. Support for odd/vs even.

**Comment by kausandr** [comment]
Made range and EVEN/ODD mapping support.

range separator is ':'

sample:

<field-map source=":99" target="UNDEFINED_L" type="Range"/>
<field-map source="100:206" target="SUCCESS" type="Range"/>
<field-map source="300:308" target="WARNING" type="Range"/>
<field-map source="400" target="ERROR" type="Range"/> 
<field-map source="401:" target="UNDEFINED_U" type="Range"/>
<field-map source="310" target="UNDEFINED_INNER"/> 
<field-map source="Odd" target="SOME_ODD_NUMBER_FOUND" type="Calc"/>
<field-map source="EVEN" target="SOME_EVEN_NUMBER_FOUND" type="Calc"/>
