### ISSUE TITLE
provide method to suppress MQ trace operations (i.e. MQOPEN, MQCLOSE,  MQCONNECT, MQDISCONNECT, MQCONNECT_X )

### ISSUE THREAD

**Issue by igorkry** [Nastel/tnt4j-streams#20]
similarly to #19 client applications issue MQOPEN, MQCLOSE,  MQCONNECT, MQDISCONNECT, MQCONNECT_X and etc. that could cause overflow.

need a method to suppress unwanted MQ trace operations

**Comment by kausandr** [comment]
Use stream property `TraceOperations`. See commented out lines of sample stream confuguration.
