### ISSUE TITLE
tnt4j stream converts Correl_ID field with "x0"

### ISSUE THREAD

**Issue by igorkry** [Nastel/tnt4j-streams#22]
example of MQ Activity Trace-
 MonitoringType: MQI Activity Trace
Correl_id:
00000000:  414D 5143 4147 4E54 3120 2020 2020 2020  'AMQCAGNT1       '
00000010:  865A A758 2027 A116                      '†Z§X '¡.        '

stream conversion example -
MQCFBS (com.ibm.mq.headers.internal.store.ByteStore [encoding: 0x00000001, ccsid: 1208, size: 40] @542337171)
	MQLONG Type: 9 (0x00000009)
	MQLONG StrucLength: 40 (0x00000028)
	MQLONG Parameter: 7011 (MQBACF_CORREL_ID)
	MQLONG StringLength: 24 (0x00000018)
	MQBYTE[] String: 0x414d514341474e543120202020202020dd989b58204f8037

**Comment by kausandr** [comment]
it is WMQ lib representis binary data as `0x`. streams just prints string WMQ libs provide. 

Data is same as you see, just different view: some HEX View component on top and binary data string `0x` at the bottom.

**Comment by rnikula** [comment]
The key is not just the technical details but it needs to work within the scope of the correlating data from other sources.   The same values are produced in other places and if they differ, they won't.

**Comment by kausandr** [comment]
@igorkry: what is particular problem? just leading `0x`? or you want binary value to be represented as string?

**Comment by kausandr** [comment]
made streams not to add `0x` by default. If needed `0x` prefix - use transformation
