### ISSUE TITLE
handle cases where MQ application events include > 1 event per message 

### ISSUE THREAD

**Issue by rnikula** [Nastel/tnt4j-streams#23]
When setting up application activity events, the user has the option to set the number of events which can be sent in a single message.   This is done to optimize the message traffic by reducing the number of messages. 

While it can be set to 1, which sends a single event per message, the customer should have the ability to set this to a higher setting.

**Comment by kausandr** [comment]
"Message" is Jkool message or MQ message?

**Comment by rnikula** [comment]
message is MQ message, as received as input into TNT4j (the output format is independent)

**Comment by kausandr** [comment]
I guess wrong stream type is used:

* PCF stream makes one jKool event from one MQ message. 
* Trace stream makes as many JKool events as there are `MQCFGR` type parameters `MQGACF_ACTIVITY_TRACE` in one MQ message.

**Comment by kausandr** [comment]
It may be also the case when you see only one JKool event for one MQ message with multiple traces - only one trace matches you stream configuration and rest are filtered out.

**Comment by kausandr** [comment]
Turns out it is all about `Message` field contetnts for traces not setting data to this field.

**Comment by kausandr** [comment]
`Message` field now is filled with RAW activity data if only parser configuration property `UseActivityDataAsMessageForUnset` is set to `true`.

Activity traces PCF message RAW data now contains only particular activity trace data.
