### ISSUE TITLE
need to support concatenating fields that use transformation.    

### ISSUE THREAD

**Issue by igorkry** [Nastel/tnt4j-streams#29]
An example below
need to support concatenating fields that use transformation.    

        <field name="MFT_SRC_FILE_NAME" locator="/transaction/transferSet/item/source/file" locator-type="Label">
            <field-transform name="fileName" lang="xpath">
                ts:getFileName($fieldValue)
            </field-transform>
        </field>
        <field name="MFT_DST_FILE_NAME" locator="/transaction/transferSet/item/destination/file" locator-type="Label">
            <field-transform name="fileName" lang="xpath">
                ts:getFileName($fieldValue)
            </field-transform>
        </field>

concatenate two results as this field
<field name="ResourceName" separator=".">

**Comment by kausandr** [comment]
```xml
       <field name="XXXXXXXXXXXXXX" separator=":">
            <field-locator locator="/transaction/transferSet/item/source/file" locator-type="Label">
                <field-transform name="sFileName" lang="xpath">
                    ts:getFileName($fieldValue)
                </field-transform>
            </field-locator>
            <field-locator locator="/transaction/transferSet/item/destination/file" locator-type="Label">
                <field-transform name="tFileName" lang="xpath">
                    ts:getFileName($fieldValue)
                </field-transform>
            </field-locator>
        </field>
```
