### ISSUE TITLE
SWIFT-style message cannot be parsed with Name-Value parser

### ISSUE THREAD

**Issue by howardc2** [Nastel/tnt4j-streams#33]
In reference to my earlier opened issue "Name-Value parser does not handle new line char (or in regex) as FieldDelim or ValueDelim correctly", a real SWIFT msg format has no space delimiter between the SWIFT tag and the field value and no semi-colon at the end of the line, eg.
  :33A:BankOfParis
  :25:234.00DLR
   etc
I cannot find a combination of FieldDelim and ValueDelim to properly parse the msg.

**Comment by kausandr** [comment]
try using this:

**Comment by kausandr** [comment]
Improved `ActivityNameValueParser` allowing to define `EntryPattern` parameter. 

* EntryPattern - pattern used to to split data into name/value pairs. It should define two RegEx groups named `key` and `value` used to 
 map data contained values to name/value pair. **NOTE:** this parameter takes preference on `FieldDelim` and `ValueDelim` parameters. 

```xml
<parser name="SWIFT_NV_Msg_Data_parser" class="com.jkoolcloud.tnt4j.streams.parsers.ActivityNameValueParser">
        <property name="EntryPattern"><![CDATA[:(?<key>.*?):(?<value>.[^:]+)]]></property>
        <property name="ActivityDelim" value="EOF"/>

        <field name="EventName" value="Swift Transaction"/>
        <field name="TransID" locator="33A" locator-type="Label"/>
        <field name="TransType" locator="24B" locator-type="Label"/>
        <field name="TransValue" locator="35J" locator-type="Label"/>
        <field name="UserData" separator=":">
            <field-locator locator="57J" locator-type="Label"/>
            <field-locator locator="36" locator-type="Label"/>
        </field>
    </parser>
```

**Comment by howardc2** [comment]
Above SWIFT NameValue msg parser worked perfectly, including extraction of a multi-line value string, each line ending with NL.
