### ISSUE TITLE
ActivityXmlParser fails to parse if msg contains default namespace (ns) without ns prefix

### ISSUE THREAD

**Issue by howardc2** [Nastel/tnt4j-streams#35]
The XML test msg as shown with the given source parser spec fails to parse. But if the namespace attribute is changed to add a namespace prefix, i.e "xmlns:mybank=..."  or if the entire XML namespace attribute is removed, then the msg parses correctly.

Test Msg
============
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Request xmlns="http://www.mybank.com/EPH/BankRequest">
 <header>
   <amount>TEST30-0.01</amount>
   <sender>HISBANK</sender>
   <currency>USD</currency>
 </header>
 <genericTransFields>
   <type>SWF202 OUTBOUND </type>
   <receiver>MYBANK FRANKFURT FRANKFURT BRANCH</receiver>
   <userRef>TEST30-QT06171612-1</userRef>
 </genericTransFields>
</Request>

Parser source .xml
================
<parser name="MYBANK_XML_Msg_Data_parser" class="com.jkoolcloud.tnt4j.streams.parsers.ActivityXmlParser">
    <field name="EventName" value="MYBANK XML Transaction"/>
    <field name="TransID"    locator="/Request/genericTransFields/userRef" locator-type="Label"/>
    <field name="TransType"  locator="/Request/genericTransFields/type"    locator-type="Label"/>
    <field name="TransValue" separator=":" >
	 <field-locator    locator="/Request/header/amount"    locator-type="Label"/>
	 <field-locator    locator="/Request/header/currency"  locator-type="Label"/>
    </field>	
</parser>
....

	<field name="MessageDataText10" locator="MQGACF_ACTIVITY_TRACE.MQBACF_MESSAGE_DATA" locator-type="Label" datatype="String"
               format="string" transparent="true">
            <parser-ref name="MYBANK_XML_Msg_Data_parser" aggregation="Merge"/>			
        </field>

Howard

**Comment by kausandr** [comment]
Register namespace for a parser using `Namespace` property like this:
```xml
        <property name="Namespace" value="mybank=http://www.approuter.com/schemas/2008/1/orcmon"/>
```

**Comment by kausandr** [comment]
rebuild with changes from last commit.

use parser property:
```xml
<property name="NamespaceAware" value="false"/>
```
to disable XML (default) namespaces support by parser.

**Comment by howardc2** [comment]
Even if an XML parser specification leaves out the "NamespaceAware = true," property, a default namespace line in the msg does not require a namespace "prefix" and the XML activity parser should allow for that.

**Comment by kausandr** [comment]
Java XPath always requires namespace definition for tags with default namespace. See this [stackoverflow topic](https://stackoverflow.com/questions/1730710/xpath-is-there-a-way-to-set-a-default-namespace-for-queries)
