### ISSUE TITLE
Include support for data transformation rules

### ISSUE THREAD

**Issue by jbnas** [Nastel/tnt4j-streams#4]
Add support for data transformation rules to tnt4j-streams.  This would allow the raw data, after being extracted based on the locator rules, to be altered, or transformed, before sending to jKool.

The simple use case is that the raw data being extracted is a full file name path, but only the simple file name is wanted.  However, this needs to support potentially complex transformations, including chains of transformations.

One thought was to add support for `<field-transform>` elements under a `<field>` and `<field=locator>` elements.  These would be applied after all other items, like `<field-map>`.  If `<field-transform>` elements was directly under `<field>` element, then it would apply to the complete field value, after all locators are processed.  If under a `<field-locator>` element, then would apply only to the value extracted by that locator.

If multiple `<field-transform>` elements, they are applied sequentially, as defined in configuration, with the input for each transform being the output of the previous one.

**Comment by kausandr** [comment]
Now wandering how would be better...

1) Should we implement some functions set (like XPath has) to use in those <field-tranform> elements. Direct use of XPath API is not efficient because functions uses XPathContext as parameter and returns XObject as result.

2) We could allow user to define transformation using some scripting language i.e. using groovy.

**Comment by kausandr** [comment]
transformations can be:
* script/expression based: `groovy`, `javascript`, `xpath`
  * it is possible to extend `xpath` expressions by implementing custom functions. now there is one custom function `getFileName`.
* referencing bean implementing `ValueTransformation` interface.

see sample `tnt4j-streams-core\samples\single-log-transformations`.

more details on transformations will be provided in Readme.md file.
