### ISSUE TITLE
support for MQ 9.0.5 log enhancements

### ISSUE THREAD

**Issue by rnikula** [Nastel/tnt4j-streams#42]
IBM added JSON formatted logs in 9,0,5 which may simplify log analysis.  We should provide the ability to support them directly

https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.pro.doc/q130630_.htm#q130630___errlog

**Comment by kausandr** [comment]
IBM MQ error logs JSON parsing sample added.
