### ISSUE TITLE
support for generic and multiple include/exclude filters 

### ISSUE THREAD

**Issue by rnikula** [Nastel/tnt4j-streams#47]
Currently, for a given field, you can specify filters but often times you want to include/exclude multiple values.   Include/Exclude Saturday/Sunday.    However, if specified, only 1 value is recognized.  A list or multiple values should be supported. 

Similarly, in many cases, the desire is to use a mask to filter.    Include/Exclude everything from PROD where PROD could be a regular expression.

**Comment by mjok** [comment]
Found a bug handling multiple INCLUDES
